{% set name = "jupyterlab-slurm" %}

# Made up version name for fork
{% set version = "3.0.3a" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  git_url: https://github.com/anaconda/jupyterlab-slurm.git

build:
  # only build on linux64 b/c of noarch
  skip: true # [not linux64]
  noarch: python
  number: 0
  script: python -m pip install --no-deps --no-build-isolation -vv .

requirements:

# todo: I had a lot of problems with things in the build section so i put
# everything under host.  


#  build:
  host:
    - git
    - hatchling
    - nodejs >=14.0
    - hatch-nodejs-version >=0.3.2
    - hatch-jupyter-builder >=0.5
    - python
    - pip
    - setuptools >=40.8.0
    - jupyter_packaging >=0.7.9
    - jupyter_server >=2.0.1,<3
    - jupyterlab >=4.0.0,<5
  run:
    - python
    - jupyterlab 4.*

  run_constrained:
    - jupyterlab 4.*

#test:
#  requires:
#    - pip
#  imports:
#    - SSHLibrary
#  commands:
#    - pip check

about:
  home: https://github.com/anaconda/jupyterlab-slurm
  license: "LICENSE"
  summary: "A JupyterLab extension that interfaces with the Slurm Workload Manager, providing simple and intuitive controls for viewing and managing jobs on the queue."

extra:
  skip-lints:
    - avoid_noarch
  anaconda-services:
    comment: "Built for JupyterHub slurm"
    recipe_maintainers:
      - bkreider

